# print(1, 2, 4)
# print(1, 2, 4, 6, 32, 7, 'a')
# print("Hi " + "Hello")
# print(1, 2, 3, sep='*')
# print(1, 2, 3, '_')
# print()
# print(1)
#print(1, 2, 3, end=' ')
#print(1, 2, 3, end='')

# a = input()
# print(a)

# a = input("Enter int number: ")
# b = input("Enter int number: ")
# print(a + b)

# a = input("Enter list: ")
# print(a)
# a.append('a')
